project:
  type: book
  output-dir: docs

book:
  title: "Advanced Computational Physics & Machine Learning"
  author: "Jim Brooke & Sudan Paramesvaran"
  date: "15 Sept 2025"
  chapters:
    - index.qmd
    - intro.qmd
    - adv-python.qmd
    - linear-algebra.qmd
    - monte-carlo.qmd
    - intro-ml.qmd
 #   - supervised-ml.qmd
    - neural-networks.qmd
 #   - unsupervised-ml.qmd

bibliography: references.bib

crossref:
  chapters: true 

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



